const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.custom,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Fondo: 0},
	{Desvanecer: 0},
	{Texto: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Bala: 0},
	{DesplazarHasta: 0},
	{"8Direcciones": 0},
	{Personalizado: 0},
	{Nave: 0},
	{Girar: 0},
	{Ateroide: 0},
	{Teclado: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Fondo2: 0},
	{Sprite4: 0},
	{FondoEnMosaico: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{FondoEnMosaico2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Again: 0}
];

self.InstanceType = {
	Fondo: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Nave: class extends self.ISpriteInstance {},
	Ateroide: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Fondo2: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Again: class extends self.IButtonInstance {}
}